using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace backend_service.Models;

/// <summary>
/// A physical microgrid node. One document per station in the
/// <c>SolarStationInfo</c> collection.
/// </summary>
public sealed class SolarStationInfo
{
    /// <summary>Machine identifier. Generated by the server, never accepted from a client.</summary>
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string? Id { get; set; }

    /// <summary>
    /// Human-facing unique identifier used on labels and reports. Immutable once
    /// the station exists, because operators print it and quote it.
    /// </summary>
    [BsonElement("stationCode")]
    public string StationCode { get; set; } = string.Empty;

    [BsonElement("name")]
    public string Name { get; set; } = string.Empty;

    [BsonElement("description")]
    [BsonIgnoreIfNull]
    public string? Description { get; set; }

    [BsonElement("addressLine")]
    [BsonIgnoreIfNull]
    public string? AddressLine { get; set; }

    [BsonElement("latitude")]
    public double Latitude { get; set; }

    [BsonElement("longitude")]
    public double Longitude { get; set; }

    [BsonElement("capacityKWh")]
    public double CapacityKWh { get; set; }

    [BsonElement("totalBatterySlots")]
    public int TotalBatterySlots { get; set; }

    [BsonElement("availableBatterySlots")]
    public int AvailableBatterySlots { get; set; }

    [BsonElement("status")]
    [BsonRepresentation(BsonType.String)]
    public StationStatus Status { get; set; } = StationStatus.Active;

    [BsonElement("operationalSchedule")]
    public List<OperationalScheduleEntry> OperationalSchedule { get; set; } = new();

    [BsonElement("contactPhone")]
    [BsonIgnoreIfNull]
    public string? ContactPhone { get; set; }

    // ── Audit ────────────────────────────────────────────────────────────────
    // All of these are server-set. Values supplied by a client are discarded.

    [BsonElement("createdAtUtc")]
    public DateTime CreatedAtUtc { get; set; }

    [BsonElement("createdByUserId")]
    public string CreatedByUserId { get; set; } = string.Empty;

    [BsonElement("updatedAtUtc")]
    [BsonIgnoreIfNull]
    public DateTime? UpdatedAtUtc { get; set; }

    [BsonElement("updatedByUserId")]
    [BsonIgnoreIfNull]
    public string? UpdatedByUserId { get; set; }

    [BsonElement("deactivatedAtUtc")]
    [BsonIgnoreIfNull]
    public DateTime? DeactivatedAtUtc { get; set; }

    [BsonElement("deactivationReason")]
    [BsonIgnoreIfNull]
    public string? DeactivationReason { get; set; }
}
